### ISSUE TITLE
Warn or inform regarding cryptographic validations

### ISSUE THREAD

**Issue by globalcitizen** [gentoo/gentoo-docker-images#59]
On my environment although the build succeeds I receive errors regarding cryptographic validation as follows.

```
STAGE3PATH: 20180403T214502Z/stage3-amd64-20180403T214502Z.tar.xz
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key BB572E0E2D182910: 7 signatures not checked due to missing keys
gpg: key BB572E0E2D182910: 1 bad signature
gpg: key BB572E0E2D182910: public key "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Wed Apr  4 02:04:17 2018 UTC
gpg:                using RSA key 13EBBDBEDE7A12775DFDB1BABB572E0E2D182910
gpg: Good signature from "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 13EB BDBE DE7A 1277 5DFD  B1BA BB57 2E0E 2D18 2910
stage3-amd64-20180403T214502Z.tar.xz: OK
stage3-amd64-20180403T214502Z.tar.xz.CONTENTS: OK
Removing intermediate container 27a24686e6f2
```

**Comment by globalcitizen** [comment]
Just tested - after setting up my local keyring as per https://www.gentoo.org/downloads/signatures/ there was still no validation made. Unless I am missing something in the code, this implies that none of these 'official' builds are cryptographically validated. That is a bit of a worry.

**Comment by thesamesam** [comment]
This was actually a confusing/misleading message based on how we weere doing signatures. It was fine, but an unusual layout.

Note:
```
gpg: Good signature from "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

It's saying this because you have not told gpg you personally trust the key. But it is saying the signature is from that key.

We've now [changed to a more standard](https://www.gentoo.org/news/2022/02/17/changed-signatures.html) format (.asc) files, see also https://github.com/gentoo/gentoo-docker-images/commit/7aea4fa952454731779696bda1fdd3d605b8f07b. Let me know if you still have concerns, but I promsie, they are indeed validated.
